// <auto-generated />
namespace Taskever.Infrastructure.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Heirarchy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Heirarchy));
        
        string IMigrationMetadata.Id
        {
            get { return "201603090026043_Heirarchy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
