// <auto-generated />
namespace Taskever.Infrastructure.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ActivityType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActivityType));
        
        string IMigrationMetadata.Id
        {
            get { return "201603051230388_ActivityType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
